# add_newline = false

[aws]
disabled = true

[cmd_duration]
show_notifications = true

[directory]
truncate_to_repo = false
truncation_symbol = "â€¦/"

[jobs]
disabled = true

[gcloud]
disabled = true

[git_status]
conflicted = '!'
modified = '*'
untracked = '' # ignore unknown files present

[shlvl]
disabled = false

[status]
format = '[$symbol:$status]($style)'
disabled = false

[username]
disabled = false
show_always = true
